development: &default
  adapter: mysql2
  database: group_diz_dev
  pool: 25
  timeout: 5000
  encoding: utf8

production:
  <<: *default
  database: group_diz_production

test: &test
  <<: *default
  database: group_diz_test
  pool: 5
  timeout: 5000
